societe-generale/ci-droid-tasks-consumer

ci-droid-tasks-consumer-autoconfigure/pom.xml
ci-droid-tasks-consumer-infrastructure/pom.xml
ci-droid-tasks-consumer-infrastructure/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/ActionToPerformListener.java
ci-droid-tasks-consumer-infrastructure/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/FeignRemoteGitHub.java
ci-droid-tasks-consumer-services/pom.xml
ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/ActionNotificationService.java
ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/ActionToPerformService.java
ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/RemoteGitHub.java
ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/exceptions/GitHubAuthorizationException.java
ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/model/github/UpdatedResource.java
ci-droid-tasks-consumer-services/src/test/java/com/societegenerale/cidroid/tasks/consumer/services/ActionNotificationServiceTest.java
ci-droid-tasks-consumer-services/src/test/java/com/societegenerale/cidroid/tasks/consumer/services/ActionToPerformServiceTest.java
ci-droid-tasks-consumer-starter/pom.xml
pom.xml

fix for https://github.com/societe-generale/ci-droid-tasks-consumer/issues/5

Proper notification when error401

---

ci-droid-tasks-consumer-autoconfigure/src/main/resources/application.yml
ci-droid-tasks-consumer-infrastructure/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/ActionToPerformCommand.java
ci-droid-tasks-consumer-infrastructure/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/ActionToPerformListener.java
ci-droid-tasks-consumer-infrastructure/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/FeignRemoteGitHub.java
ci-droid-tasks-consumer-infrastructure/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/config/GlobalProperties.java
ci-droid-tasks-consumer-infrastructure/src/test/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/ActionToPerformListenerTest.java
ci-droid-tasks-consumer-infrastructure/src/test/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/FeignRemoteGitHubLIVETest.java
ci-droid-tasks-consumer-infrastructure/src/test/resources/application-test.yml
ci-droid-tasks-consumer-infrastructure/src/test/resources/incomingCommandWithUnknownActionType.json
ci-droid-tasks-consumer-infrastructure/src/test/resources/incomingOverWriteStaticContentAction.json
ci-droid-tasks-consumer-infrastructure/src/test/resources/incomingOverWriteStaticContentAction_withPullRequestInteraction.json
ci-droid-tasks-consumer-infrastructure/src/test/resources/incomingReplaceMavenProfileAction.json
ci-droid-tasks-consumer-infrastructure/src/test/resources/incomingSimpleReplaceActionCommand.json
ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/ActionToPerformService.java
ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/RemoteGitHub.java
ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/model/BulkActionToPerform.java
ci-droid-tasks-consumer-services/src/test/java/com/societegenerale/cidroid/tasks/consumer/services/ActionNotificationServiceTest.java
ci-droid-tasks-consumer-services/src/test/java/com/societegenerale/cidroid/tasks/consumer/services/ActionToPerformServiceTest.java

fixes https://github.com/societe-generale/ci-droid-tasks-consumer/issues/8

Making it work with github.com

---

ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/ActionToPerformService.java
ci-droid-tasks-consumer-services/src/test/java/com/societegenerale/cidroid/tasks/consumer/services/ActionToPerformServiceTest.java
pom.xml

Issue15 handle pull request name

---

CHANGELOG.md
ci-droid-tasks-consumer-infrastructure/src/test/resources/actionToPerformLive.json
ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/ActionToPerformService.java
ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/model/github/Reference.java
ci-droid-tasks-consumer-services/src/test/java/com/societegenerale/cidroid/tasks/consumer/services/ActionToPerformServiceTest.java

fixes https://github.com/societe-generale/ci-droid-tasks-consumer/issues/17

Create PR on top of provided branch

---

ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/ActionToPerformService.java
ci-droid-tasks-consumer-services/src/test/java/com/societegenerale/cidroid/tasks/consumer/services/ActionToPerformServiceTest.java
ci-droid-tasks-consumer-services/src/test/java/com/societegenerale/cidroid/tasks/consumer/services/TestActionToPerform.java

avoid NPEs when providing content for certain actionToReplicate

---

ci-droid-tasks-consumer-autoconfigure/src/main/resources/application-development.yml
ci-droid-tasks-consumer-autoconfigure/src/main/resources/application.yml
ci-droid-tasks-consumer-infrastructure/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/FeignRemoteGitHub.java

now configuring Oauth token for all github interactions in FeignClient

---

ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/PushEventOnDefaultBranchService.java
ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/actionHandlers/RebaseHandler.java
ci-droid-tasks-consumer-services/src/test/java/com/societegenerale/cidroid/tasks/consumer/services/PushEventOnDefaultBranchServiceTest.java

fixes #25 
now catching exception around each event handler call, so that even if one fails, others will be called.

now catching exception around each event handler call

---

ci-droid-tasks-consumer-autoconfigure/src/main/java/com/societegenerale/cidroid/tasks/consumer/autoconfigure/CiDroidTasksConsumerAutoConfiguration.java
ci-droid-tasks-consumer-infrastructure/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/config/InfraConfig.java
ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/actionHandlers/DummyPullRequestEventHandler.java
ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/actionHandlers/DummyPushEventOnDefaultBranchHandler.java

re-adding the dummy classes

---

ci-droid-tasks-consumer-services/pom.xml
ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/monitoring/Event.java
ci-droid-tasks-consumer-services/src/test/java/com/societegenerale/cidroid/tasks/consumer/services/monitoring/EventTest.java
ci-droid-tasks-consumer-services/src/test/java/com/societegenerale/cidroid/tasks/consumer/services/monitoring/TestAppender.java
ci-droid-tasks-consumer-services/src/test/resources/logback-test.xml

fixed logging of technical events

---

ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/ActionNotificationService.java
ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/ActionToPerformService.java
ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/model/github/PullRequest.java
ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/model/github/UpdatedResource.java
ci-droid-tasks-consumer-services/src/test/java/com/societegenerale/cidroid/tasks/consumer/services/ActionNotificationServiceTest.java
ci-droid-tasks-consumer-services/src/test/java/com/societegenerale/cidroid/tasks/consumer/services/ActionToPerformServiceTest.java

dont open a PR if an open one on same branch already exists

---

ci-droid-tasks-consumer-infrastructure/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/ActionToPerformCommand.java
ci-droid-tasks-consumer-infrastructure/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/ActionToPerformListener.java
ci-droid-tasks-consumer-infrastructure/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/FeignRemoteGitHub.java
ci-droid-tasks-consumer-infrastructure/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/config/InfraConfig.java
ci-droid-tasks-consumer-infrastructure/src/test/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/ActionToPerformListenerTest.java
ci-droid-tasks-consumer-infrastructure/src/test/resources/incomingOverWriteStaticContentAction.json
ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/ActionNotificationService.java
ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/ActionToPerformService.java
ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/RemoteGitHub.java
ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/model/BulkActionToPerform.java
ci-droid-tasks-consumer-services/src/test/java/com/societegenerale/cidroid/tasks/consumer/services/ActionNotificationServiceTest.java
ci-droid-tasks-consumer-services/src/test/java/com/societegenerale/cidroid/tasks/consumer/services/ActionToPerformServiceTest.java

now retrieving user details from API

---

CHANGELOG.md
ci-droid-tasks-consumer-infrastructure/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/FeignRemoteGitHub.java
ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/ActionNotificationService.java
ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/ActionToPerformService.java
ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/RemoteGitHub.java
ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/model/github/UpdatedResource.java
ci-droid-tasks-consumer-services/src/test/java/com/societegenerale/cidroid/tasks/consumer/services/ActionNotificationServiceTest.java
ci-droid-tasks-consumer-services/src/test/java/com/societegenerale/cidroid/tasks/consumer/services/ActionToPerformServiceTest.java

bulkAction - specific notification when repo doesn't exist 

---

README.md

Adding the code coverage percentage on the readme

Adding coverage status badge

---

CHANGELOG.md
ci-droid-tasks-consumer-autoconfigure/pom.xml
ci-droid-tasks-consumer-autoconfigure/src/main/java/com/societegenerale/cidroid/tasks/consumer/autoconfigure/CiDroidTasksConsumerAutoConfiguration.java
ci-droid-tasks-consumer-autoconfigure/src/main/resources/application.yml
ci-droid-tasks-consumer-infrastructure/pom.xml
ci-droid-tasks-consumer-infrastructure/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/FeignRemoteGitHub.java
ci-droid-tasks-consumer-infrastructure/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/config/CiDroidBehavior.java
ci-droid-tasks-consumer-infrastructure/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/config/InfraConfig.java
ci-droid-tasks-consumer-infrastructure/src/test/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/TestConfig.java
ci-droid-tasks-consumer-infrastructure/src/test/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/YamlFileApplicationContextInitializer.java
ci-droid-tasks-consumer-infrastructure/src/test/resources/application-test.yml
ci-droid-tasks-consumer-services/pom.xml
ci-droid-tasks-consumer-starter/pom.xml
pom.xml

spring boot 2 upgrade

---

ci-droid-tasks-consumer-autoconfigure/pom.xml
ci-droid-tasks-consumer-autoconfigure/src/main/java/com/societegenerale/cidroid/tasks/consumer/autoconfigure/CiDroidTasksConsumerApplication.java
ci-droid-tasks-consumer-infrastructure/src/test/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/YamlFileApplicationContextInitializer.java
ci-droid-tasks-consumer-starter/pom.xml
pom.xml

Upgraded the Spring Boot version to 2.1.1 as suggested in issue #49.
Spring Cloud was also upgraded to Finchley.
Several other little upgrades.

Upgrade dependency versions

---

ci-droid-tasks-consumer-autoconfigure/pom.xml

adding actuator to get a healthcheck endpoint available

---

ci-droid-tasks-consumer-infrastructure/pom.xml
ci-droid-tasks-consumer-starter/pom.xml
pom.xml

See #66 
I temporarily set the spring-boot-maven-plugin version to 2.1.3.RELEASE since it doesn't have a 2.2.0 version yet.

Upgrade to Spring Boot 2.2.0.M1

---

ci-droid-tasks-consumer-autoconfigure/src/main/java/com/societegenerale/cidroid/tasks/consumer/autoconfigure/CiDroidTasksConsumerAutoConfiguration.java
ci-droid-tasks-consumer-infrastructure/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/GitHubEventDeserializer.java
ci-droid-tasks-consumer-infrastructure/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/GitHubeventDeserializer.java
ci-droid-tasks-consumer-infrastructure/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/GitLabEventDeserializer.java
ci-droid-tasks-consumer-infrastructure/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/SourceControlEventListener.java
ci-droid-tasks-consumer-infrastructure/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/SourceControlEventMapper.java
ci-droid-tasks-consumer-infrastructure/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/config/GitHubConfig.java
ci-droid-tasks-consumer-infrastructure/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/config/GitLabConfig.java
ci-droid-tasks-consumer-infrastructure/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/config/InfraConfig.java
ci-droid-tasks-consumer-infrastructure/src/test/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/GithubEventListenerLIVETest.java
ci-droid-tasks-consumer-infrastructure/src/test/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/GithubEventListenerTest.java
ci-droid-tasks-consumer-infrastructure/src/test/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/TestConfig.java
ci-droid-tasks-consumer-infrastructure/src/test/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/handlers/PullRequestCleaningIT.java
ci-droid-tasks-consumer-infrastructure/src/test/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/handlers/PullRequestNotificationsIT.java
ci-droid-tasks-consumer-infrastructure/src/test/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/handlers/PullRequestRebaseIT.java
ci-droid-tasks-consumer-infrastructure/src/test/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/handlers/SourceControlEventHandlerIT.java
ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/model/PullRequestEvent.java
ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/model/PushEvent.java
ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/model/SourceControlEvent.java
ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/model/github/GitHubPullRequestEvent.java
ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/model/github/GitHubPushEvent.java
ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/model/gitlab/GitLabMergeRequestEvent.java
ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/model/gitlab/GitLabPushEvent.java

refactored to deserialize gitlab and github events, while preserving the original event

ready to monitor original events

---

CHANGELOG.md
ci-droid-tasks-consumer-autoconfigure/src/main/java/com/societegenerale/cidroid/tasks/consumer/autoconfigure/CiDroidTasksConsumerAutoConfiguration.java
ci-droid-tasks-consumer-autoconfigure/src/main/resources/application-development.yml
ci-droid-tasks-consumer-autoconfigure/src/main/resources/application.yml
ci-droid-tasks-consumer-infrastructure/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/config/GitHubConfig.java
ci-droid-tasks-consumer-infrastructure/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/config/GitLabConfig.java
ci-droid-tasks-consumer-infrastructure/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/config/GlobalProperties.java
ci-droid-tasks-consumer-infrastructure/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/config/InfraConfig.java
ci-droid-tasks-consumer-infrastructure/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/config/SourceControlConfig.java
ci-droid-tasks-consumer-infrastructure/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/config/SourceControlType.java
ci-droid-tasks-consumer-infrastructure/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/github/FeignRemoteGitHub.java
ci-droid-tasks-consumer-infrastructure/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/github/GitHubEventDeserializer.java
ci-droid-tasks-consumer-infrastructure/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/gitlab/GitLabClient.java
ci-droid-tasks-consumer-infrastructure/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/gitlab/GitLabEventDeserializer.java
ci-droid-tasks-consumer-infrastructure/src/test/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/GithubEventListenerTest.java
ci-droid-tasks-consumer-infrastructure/src/test/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/handlers/PullRequestRebaseIT.java
ci-droid-tasks-consumer-infrastructure/src/test/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/rest/TestApplication.java
ci-droid-tasks-consumer-infrastructure/src/test/resources/application-test.yml

instead, using an explicit property in the config

not using profiles anymore to load source control specific config

---

ci-droid-tasks-consumer-github-adapter/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/github/model/GitHubPushEvent.java
ci-droid-tasks-consumer-gitlab-adapter/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/gitlab/model/GitLabPushEvent.java
ci-droid-tasks-consumer-services/src/main/java/com/societegenerale/cidroid/tasks/consumer/services/model/PushEvent.java
ci-droid-tasks-consumer-services/src/test/java/com/societegenerale/cidroid/tasks/consumer/services/TestPushEvent.java

getRawEvent was removed by mistake in 2.0.0

adding rawEvent in interface

---

ci-droid-tasks-consumer-bitbucket-adapter/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/bitbucket/FeignRemoteForBitbucketBulkActions.java
ci-droid-tasks-consumer-bitbucket-adapter/src/main/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/bitbucket/RemoteForBitbucketBulkActionsWrapper.java
ci-droid-tasks-consumer-bitbucket-adapter/src/test/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/bitbucket/RemoteForBitbucketBulkActionsWrapperTest.java
ci-droid-tasks-consumer-bitbucket-adapter/src/test/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/bitbucket/mocks/BitBucketMockServer.java

Issue - 100 - Fix for Latest Source Sha key of the file (https://github.com/societe-generale/ci-droid-tasks-consumer/issues/100)
